redbrickboard/event_management/urls.py
from django.urls import path

from .views import EventListView, EventDetailView, EventCreateView, EventUpdateView, FeaturedEventListView, delete_image, search_events, bump_event, event_rsvp, handle_attendance



urlpatterns = [
    path('', EventListView.as_view(), name='event-list'),
    path('<int:pk>/', EventDetailView.as_view(), name='event-details'),
    path('create/', EventCreateView.as_view(), name='event-create'),
    path('<int:pk>/update/', EventUpdateView.as_view(), name='event-update'),
    path('featured/', FeaturedEventListView.as_view(), name='event-featured'),
    path('int<pk>/delete-image/', delete_image, name='delete_image'),
    path('search', search_events, name='event-search'),
    path('<int:pk>/bump-event', bump_event, name="bump-event"),
    path('<int:pk>/rsvp', event_rsvp, name='event-rsvp'),
    path('<int:pk>/handle-attendance', handle_attendance, name='event-attendance'),
]

app_name = "event_management"

redbrickboard/home/urls.py
from django.urls import path

from .views import EventHomeListView

urlpatterns = [
    path('', EventHomeListView.as_view(), name='home'),
]

redbrickboard/redbrickboard/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("events/", include("event_management.urls", namespace='event_management')),
    path("", include('home.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

redbrickboard/event_management/models.py
import os
from django.db import models
from django_resized import ResizedImageField
from django.utils import timezone
from django.urls import reverse
from accounts import models as accounts
from uuid import uuid4

# from datetime import timedelta

class Event(models.Model):
    event_name = models.CharField(default='', max_length=150, verbose_name='Event Name')
    event_description = models.TextField(default='', max_length=500, verbose_name='Event Description')
    event_datetime_start = models.DateTimeField(default=timezone.now, null=False, verbose_name='Start Date & Time of the Event')
    event_datetime_end = models.DateTimeField(default=None, null=True, verbose_name='End Date & Time of the Event')
    event_organizer = models.ForeignKey(accounts.CustomUser, on_delete=models.CASCADE, related_name='events_organized', verbose_name='Event Organizer')
    event_header = ResizedImageField(quality=75, force_format='WebP', upload_to='headers/', verbose_name='Banner Image of the Event')
    event_venue = models.CharField(default='', max_length=125, verbose_name='Event Venue')
    last_time_bumped = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '{}'.format(self.event_name)
    
    def get_absolute_url(self):
        return reverse('event_management:event-details', kwargs={'pk': self.pk})
    
    def get_update_url(self):
        return reverse('event_management:event-update', kwargs={'pk': self.pk})

    ## An event can be bumped if it has been 2 days since the last bump
    @property
    def can_be_bumped(self):
        time_difference = timezone.now() - self.last_time_bumped
        days_difference = time_difference.total_seconds() // (60 * 60 * 20)
        if days_difference >= 2:
            return True
        return False
    
    # checks if an event is upcoming/ongoing or in the past.
    @property
    def is_upcoming(self):
        time_difference = timezone.now() - self.event_datetime_end
        if time_difference.total_seconds() < 0:
            # If the event is upcoming/ongoing, return True
            return True
        return False


class Promo(models.Model):
    event = models.ForeignKey(
        Event,
        related_name="promos",
        on_delete=models.CASCADE,
        null=True)
    img = ResizedImageField(quality=75, force_format='WebP', upload_to='promos/')

    def __str__(self):
        return self.event.event_name
    
    def get_absolute_url(self):
        return reverse('event_management:event-details', kwargs={'pk': self.pk})

# class Comment(models.Model):
#     event_name = models.ForeignKey(Event, on_delete=models.CASCADE)
#     event_commenter = models.ForeignKey(accounts.CustomUser, default='', on_delete=models.CASCADE, related_name='event_commenter')
#     event_comment = models.TextField(default='', max_length=255)
#     comment_created = models.DateTimeField(default=timezone.now, null=False)
#     comment_updated = models.DateTimeField(default=timezone.now, null=False)
    
#     class Meta:
#         ordering = ['-comment_updated']
    
#     def __str__(self):
#         return 'Comment by {}: {}'.format(self.event_commenter, self.event_comment)
    

class Attendance(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='events_attended')
    attendee = models.ForeignKey(accounts.CustomUser, on_delete=models.CASCADE, related_name='events_attendee')
    has_attended = models.BooleanField(default=False)

redbrickboard/event_management/forms.py
from accounts import models as accounts
from django import forms
from django.forms import ModelForm, BaseModelFormSet, inlineformset_factory
from .models import Event, Promo

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = "__all__"
        exclude = ('last_time_bumped', 'event_organizer',)
        widgets = {
            'event_datetime_start':forms.TextInput(attrs={'type':'datetime-local'}),
            'event_datetime_end':forms.TextInput(attrs={'type':'datetime-local'}),
            'last_time_bumped':forms.TextInput(attrs={'type':'datetime-local'}),
        }

class PromoForm(ModelForm):
    model = Promo
    fields = "__all__"


# Source for the whole formset integration:
# https://www.letscodemore.com/blog/django-inline-formset-factory-with-examples/

PromoFormSet = inlineformset_factory(
    Event,
    Promo,
    form=PromoForm,
    extra=1,
    fields=['img'],
    can_delete=True,
    can_delete_extra=True
)

redbrickboard/event_management/views.py
from typing import Any
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages

from .forms import (EventForm, PromoFormSet)
from .models import Event, Promo, Attendance
from django.db.models import Q 

from django.utils import timezone

from django.urls import reverse_lazy

# import to require users to be logged in to access certain features
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin

import random


# This function is for custom delete button.
def delete_image(request, pk):
    try:
        image = Promo.objects.get(id=pk)
    except Promo.DoesNotExist:
        messages.success(
            request, 'Object Does not exist'
        )
        return redirect('event_management:event-update', pk=image.event.id)

    image.delete()
    messages.success(
        request, 'Image deleted successfully'
    )
    return redirect('event_management:event-update', pk=image.event.id)


# This function is use for searching events based on their name or description. 
def search_events(request):
    if request.method == "POST":
        searched = request.POST['searched']
        events = Event.objects.all()
        events = Event.objects.filter(Q(event_name__icontains=searched)|Q(event_description__icontains=searched))

        return render(request, 'event_management/event-search.html', {'searched': searched, 'events':events})
    else:

        return render(request, 'event_management/event-search.html', {})


class PromoInline():
    form_class = EventForm
    template_name = 'event_management/event-form.html'

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))
        self.object = form.save()

        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        
        # Get the URL for the event details page
        event_details_url = reverse_lazy('event_management:event-details', kwargs={'pk': self.object.pk})
        
        return redirect(event_details_url)

    def formset_images_valid(self, formset):
        images = formset.save(commit=False)
        for obj in formset.deleted_objects:
            obj.delete()
        for image in images:
            image.event = self.object
            image.save()


class EventDetailView(DetailView):
    model = Event
    fields = '__all__'
    template_name = 'event_management/event-details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event = self.get_object()
        attendance = Attendance.objects.filter(event = event)

        context['attendance'] = attendance
        attendance = attendance.order_by('?')
        
        if attendance.count() > 4:
            context['attendance_limited'] = attendance[:4]
        else:
            context['attendance_limited'] = attendance

        return context


class EventListView(ListView):
    model = Event
    fields = '__all__'
    template_name = 'event_management/event-list.html'


class FeaturedEventListView(ListView):
    model = Event
    fields = '__all__'
    queryset = Event.objects.order_by('-last_time_bumped')[:8]
    template_name = 'event_management/event-featured.html'


# Creating an event requires the user to be logged in
class EventCreateView(LoginRequiredMixin, PromoInline, CreateView):
    login_url = '/accounts/login'
    model = Event
    
    # Set the event organizer to the currently logged-in user
    def form_valid(self, form):
        form.instance.event_organizer_id = self.request.user.pk
        messages.success(self.request, "Event successfully created!")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super(EventCreateView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx
    
    def get_named_formsets(self):
        if self.request.method == "GET":
            return{
                'images': PromoFormSet(prefix='images')
            }
        else:
            return{
                'images': PromoFormSet(self.request.POST or None, self.request.FILES or None, prefix='images')
            }


# Updating an event requires the user to be logged in 
class EventUpdateView(LoginRequiredMixin, PromoInline, UpdateView):
    login_url = '/accounts/login'
    model = Event
    form_class = EventForm 

    # Makes use of form valid function to pass success messages
    def form_valid(self, form):
        messages.success(self.request, "Event successfully updated!!")
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        ctx = super(EventUpdateView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx
    
    def get_named_formsets(self):
        return {
            'images': PromoFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='images'),
        }
    
    # Restricts the update of events to the event organizer only 
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if not obj.event_organizer == self.request.user:
            messages.error(request, "You do not have permission to update this event.")
            return redirect('event_management:event-details', pk = obj.pk)
        return super().dispatch(request, *args, **kwargs)


# Bumping an event requires the user to be logged in
@login_required(login_url="/accounts/login")
def bump_event(request, *args, **kwargs):
    # gets PK of the event
    pk = kwargs.get('pk')

    # gets Event object in Event table, based on PK
    event = get_object_or_404(Event, pk=pk)

    # gets the currently logged in user
    user = request.user

    if event.event_organizer != user:
        # this conditional ensures that non-organizers cannot bump this event
        messages.error(request, 'You do not have permission to bump this event.')
    else:
        # url can be accessed, check in place to prevent cheating bumps
        if event.can_be_bumped:
            event.last_time_bumped = timezone.now()
            event.save()
            messages.success(request, 'Bump Successful!')
        else:
            messages.error(request, 'Bump Unsuccessful. Please try again later.')

    return redirect('event_management:event-details', pk = pk) 


# To RSVP to an event, the user must be logged in
@login_required(login_url="/accounts/login")
def event_rsvp(request, *args, **kwargs):
    
    # gets PK of the event
    pk = kwargs.get('pk')
    # gets Event object in Event table, based on PK
    event = get_object_or_404(Event, pk=pk)
    # gets the currently logged in user
    user = request.user
    
    if event.event_organizer == user:
        # this conditional ensures that organizers cannot rsvp for their events
        messages.error(request, 'You may not register for this event.')
    else:
        # this conditional ensures that rsvp only happens once
        check_rsvp = Attendance.objects.filter(event = event).filter(attendee = user)
        if check_rsvp:
            messages.error(request, 'You have already registered for this event.')
        else:
            Attendance.objects.create(event = event, attendee = user)
            messages.success(request, 'RSVP Successful!')
    
    return redirect('event_management:event-details', pk = pk)


@login_required(login_url="/accounts/login")
def handle_attendance(request, *args, **kwargs):
    event_pk = kwargs.get('pk')
    event = get_object_or_404(Event, pk=event_pk)
    user = request.user

    if event.event_organizer.pk != user.pk:
        # this conditional ensures that non-organizers cannot handle attendance
        messages.error(request, 'You are not authorized to manage attendance for this event.')
    else:
        records = Attendance.objects.filter(Q(event_id=event_pk))

        attended = []
        for attendance_key, value in request.POST.items():
            if attendance_key != "csrfmiddlewaretoken":
                attended.append(int(attendance_key))

        for record in records:
            record.has_attended = 0
            if int(record.pk) in attended:
                record.has_attended = 1
            record.save()
        
        messages.success(request, 'Attendance saved!')

    return redirect('event_management:event-details', pk = event_pk)

redbrickboard/event_management/templates/event_management/event-details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ object }}{% endblock %}

{% block content %}

<div class="d-flex flex-column justify-content-center align-items-center">

    <div class="container event-container bg-light shadow overflow-hidden my-3 my-md-5">
        
        <!-- Header Image Row -->
        <div class="row">
            <div class="col mx-0 px-0">
                <img src="{{ object.event_header.url }}" class="img-fluid w-100 object-fit-cover" alt="{{ object.event_name }}">
            </div>
        </div>
    
        <!-- Event Name Row -->
        <div class="row mt-md-3 mt-2">
            <div class="col">
                <h1>{{ object.event_name }}</h1>
            </div>
        </div>

        <!-- Event Organizer Row -->
        <div class="row mb-4">
            <div class="col d-flex flex-column justify-content-end text-end">
                <h3 class="event-organizer inria-normal my-0">Organized by 
                    <a href="{{ object.event_organizer.get_absolute_url }}" 
                        class="btn border-dark text-wrap user-link rounded-pill 
                        text-decoration-underline pt-0 pb-1 px-2 mb-0"
                    >{{ object.event_organizer }}</a>
                </h3>
            </div>
        </div>

        <!-- Event Details Row -->
        <div class="row mb-3">
            <!-- Date, Time, and Venue Column -->
            <div class="col-md-6 mb-1">
                <!-- Date -->
                <div class="row">
                    <div class="col">
                        {% if object.event_datetime_start.date == object.event_datetime_end.date %}
                            <h4 class="inria-normal">Date: {{ object.event_datetime_start.date }}</h4>
                        {% else %}
                            <h4 class="inria-normal">Date: {{ object.event_datetime_start.date }} - {{ object.event_datetime_end.date }}</h4>
                        {% endif %}
                    </div>
                </div>

                <!-- Time -->
                <div class="row">
                    <div class="col">
                        {% if object.event_datetime_start.time == object.event_datetime_end.time %}
                            <h4 class="inria-normal">Time: {{ object.event_datetime_start|time:"h:i A" }}</h4>
                        {% else %}
                            <h4 class="inria-normal">Time: {{ object.event_datetime_start|time:"h:i A" }} - {{ object.event_datetime_end|time:"h:i A" }}</h4>
                        {% endif %}
                    </div>
                </div>

                <!-- Venue -->
                <div class="row">
                    <div class="col">
                        <h4 class="inria-normal">Venue: {{ object.event_venue }}</h4>
                    </div>
                </div>

            </div>

            <!-- Event Description and Button(Bump, Update, RSVP) Column -->
            <div class="col-md-6">

                <!-- Event Description -->
                <div class="row">
                    <div class="col">
                        <p class="inria-normal">{{ object.event_description }}</p>
                    </div>
                </div>

                <!-- RSVP or (Update and Bump) -->
                <div class="row">
                    <div class="col">
                        <div class="row d-flex justify-content-end">
                            {% if user.is_authenticated and user == object.event_organizer %}
                                <div class="col-auto mt-1 mb-3">                            
                                    <button 
                                        type="button" 
                                        onclick="location.href='{{ event.get_update_url }}'" 
                                        class="btn btn-blue me-2 px-4"
                                    >Update</button>
                                </div>
                                <div class="col-auto mt-1 mb-3">
                                    <button
                                        type="button"
                                        onclick="location.href='{% url 'event_management:bump-event' object.pk %}'"
                                        class="btn btn-red me-2 px-4"
                                        {% comment %} disables the button if it cannot be bumped {% endcomment %}
                                        {% if not object.can_be_bumped %} 
                                            disabled 
                                            aria-disabled="true"
                                        {% endif %}
                                    >Bump Event</button>
                                </div>
                            {% elif user != object.event_organizer %}
                                <div class="col-auto mt-1 mb-3">
                                    <button 
                                        type="button"
                                        onclick="location.href='{% url 'event_management:event-rsvp' object.pk %}'"
                                        class="btn btn-red me-2 px-4"
                                    >RSVP</button>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <!-- Display a message for bumping events -->
                <div class="row">
                    <div class="col">
                        <!-- <p>Time until bump:{{ remaining_time }}</p> -->
                        {% if user.is_authenticated and user == object.event_organizer %}
                            {% if object.can_be_bumped %}
                                <p class="text-end">Note: Promote your event by clicking the Bump Event button.</p>
                            {% else %}
                                <p class="text-end">Note: Bump the event again 2 days after your previous bump.</p>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                
            </div>

        </div>

        <!-- Promo Images Row -->
        <div class="row mb-4">
            <div class="col mt-1">
                {% for promo in object.promos.all %}
                    <img src="{{ promo.img.url }}" class="img-fluid rounded float-left mb-2 me-2" alt="promo images">
                {% endfor %}
            </div>
        </div>


        <!-- Attendee List -->
        <div class="row mb-2">
            <div class="col">
                <h3>See who's attending 👀</h3>
            </div>
        </div>

        <!-- Displays 4 users who have RSVP'd to the event -->
        <div class="row">
            {% for attendee in attendance_limited %}
                <div class="col-xl-3 col-lg-4 col-sm-6 mb-sm-1 mb-3">
                    <div class="card attendee-card h-100">
                        <img src="{{ attendee.attendee.picture.url }}" class="card-img-top ratio ratio-1x1 attendee-img mx-auto" alt="{{ attendee.attendee }}">
                        <div class="card-body mb-0 pb-0">
                            <p class="card-text attendee-text inria-normal text-center mb-0">{{ attendee.attendee }}</p>
                            <a href="{{ attendee.attendee.get_absolute_url }}" class="card-link stretched-link"></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="row mb-3">
            <div class="col me-1">
                <h3 class="text-end">...and many more!</h3>
            </div>
        </div>
     
        <!-- Attendee Check for Organizer -->
        <div class="row">
            <div class="col">
                {% if user.is_authenticated %}
                    {% if user == object.event_organizer %}
                        <h3 class="mt-4">ATTENDANCE STATUS</h3>

                        <form method="POST" action="{% url 'event_management:event-attendance' object.pk %}">
                            {% csrf_token %}
                            <div class="table-responsive">
                                <table class="table">
                                    <tr scope="col">
                                        <th>Attendee Name</th>
                                        <th class="text-center">Has Attended?</th>
                                    </tr>

                                    {% for record in attendance %}
                                        <tr>
                                            <td> {{ record.attendee }} </td>
                                            <td class="text-center">
                                                <input class="form-check-input" type="checkbox" name="{{record.pk}}" {% if record.has_attended %} checked {% endif %}/>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-red d-flex mb-4 me-2 px-4">Save Attendance</button>
                                </div>
                            </div>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        
    </div>

</div> 

{% endblock %}

redbrickboard/event_management/templates/event_management/event-list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Events{% endblock %}

{% block content %}

<div class="container-fluid mt-6 pt-5 bg-light">

    <!-- Displays Page Title as Header -->
    <div class="d-flex justify-content-center align-items-center">
        <h1>Event Catalog</h1>
    </div>

    <!-- Displays Search Function -->
    <form action="{% url 'event_management:event-search'  %}" method=POST>
        {% csrf_token %}
        <div class="form-group row justify-content-start justify-content-sm-center align-items-center mt-3 mb-5" role="search">
            <div class="col-sm-6 mb-3">
                <input class="form-control border-dark" type="search" name="searched" placeholder="Search by Event Name or Description" aria-label="Search" value="{{request.GET.title}}">
            </div>
            <div class="col-sm-auto mb-3">
                <button class="btn btn-red" type="submit" value="Search">SEARCH</button>
            </div>
            <div class="col-sm-auto mb-3">
                <a href="{% url 'event_management:event-list' %}" class="btn btn-blue" role="button">DISPLAY ALL</a>
            </div>
        </div>
    </form>

    <!-- Displays Events in Card Format -->
    <div class="row mx-md-5 mx-sm-3 mx-1">
        {% for event in object_list %}
            <div class="col-xl-3 col-lg-4 col-sm-6 mb-4">
                <div class="card h-100">
                    <img src="{{ event.event_header.url }}" class="card-img-top" alt="{{ event.event_name }}">
                    <div class="card-body d-flex flex-column px-2 py-1">
                        <h6 class="card-title mb-0">{{ event.event_name }}</h6>
                        <p class="card-text organizer inria-normal">{{ event.event_organizer }}</p>
                        {% if event.event_datetime_start.date == event.event_datetime_end.date %}
                            {% if event.event_datetime_start.time == event.event_datetime_end.time %}
                                <p class="card-text datetime inria-light align-self-end text-end mb-0 mt-auto">{{ event.event_datetime_start.date }} | {{ event.event_datetime_start|time:"h:i A" }}</p>
                            {% else %}
                                <p class="card-text datetime inria-light align-self-end text-end mb-0 mt-auto">{{ event.event_datetime_start.date }} | {{ event.event_datetime_start|time:"h:i A" }} - {{ event.event_datetime_end|time:"h:i A" }}</p>
                            {% endif %}
                        {% else %}
                            <p class="card-text datetime inria-light align-self-end text-end mb-0 mt-auto">{{ event.event_datetime_start.date }} - {{ event.event_datetime_end.date }} | {{ event.event_datetime_start|time:"h:i A" }} - {{ event.event_datetime_end|time:"h:i A" }}</p>
                        {% endif %}
                        <a href="{{ event.get_absolute_url }}" class="card-link stretched-link"></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    
</div>

{% endblock %}

redbrickboard/event_management/templates/event_management/event-search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Events{% endblock %}

{% block content %}

<div class="container-fluid mt-6 pt-5 bg-light">

    <!-- Displays Page Title as Header -->
    <div class="d-flex justify-content-center align-items-center">
        <h1>Event Catalog</h1>
    </div>

    <!-- Displays Search Function -->
    <form action="{% url 'event_management:event-search'  %}" method=POST>
        {% csrf_token %}
        <div class="form-group row justify-content-start justify-content-sm-center align-items-center mt-3 mb-5" role="search">
            <div class="col-sm-6 mb-3">
                <input class="form-control border-dark" type="search" name="searched" placeholder="Search by Event Name or Description" aria-label="Search" value="{{request.GET.title}}">
            </div>
            <div class="col-sm-auto mb-3">
                <button class="btn btn-red" type="submit" value="Search">SEARCH</button>
            </div>
            <div class="col-sm-auto mb-3">
                <a href="{% url 'event_management:event-list' %}" class="btn btn-blue" role="button">DISPLAY ALL</a>
            </div>
        </div>
    </form>

    <!-- Displays searched events in card format, or a message if the event is not found or no search entry was placed -->
    <div class="row mx-md-5 mx-sm-3 mx-1">
        {% if searched %}
            {% for event in events %}
                <div class="col-xl-3 col-lg-4 col-sm-6 mb-4">
                    <div class="card h-100">
                        <img src="{{ event.event_header.url }}" class="card-img-top" alt="{{ event.event_name }}">
                        <div class="card-body d-flex flex-column px-2 py-1">
                            <h6 class="card-title mb-0">{{ event.event_name }}</h6>
                            <p class="card-text organizer inria-normal">{{ event.event_organizer }}</p>
                            {% if event.event_datetime_start.date == event.event_datetime_end.date %}
                                {% if event.event_datetime_start.time == event.event_datetime_end.time %}
                                    <p class="card-text datetime inria-light align-self-end text-end mb-0 mt-auto">{{ event.event_datetime_start.date }} | {{ event.event_datetime_start|time:"h:i A" }}</p>
                                {% else %}
                                    <p class="card-text datetime inria-light align-self-end text-end mb-0 mt-auto">{{ event.event_datetime_start.date }} | {{ event.event_datetime_start|time:"h:i A" }} - {{ event.event_datetime_end|time:"h:i A" }}</p>
                                {% endif %}
                            {% else %}
                                <p class="card-text datetime inria-light align-self-end text-end mb-0 mt-auto">{{ event.event_datetime_start.date }} - {{ event.event_datetime_end.date }} | {{ event.event_datetime_start|time:"h:i A" }} - {{ event.event_datetime_end|time:"h:i A" }}</p>
                            {% endif %}
                            <a href="{{ event.get_absolute_url }}" class="card-link stretched-link"></a>
                        </div>
                    </div>
                </div>
                {% empty %}
                    <div class="d-flex flex-column min-vh-100">
                        <div class="flex-grow-1">
                            <h5>No matches found.</h5>
                        </div>
                    </div>
            {% endfor %}
        {% else %}
            <div class="d-flex flex-column min-vh-100">
                <div class="flex-grow-1">
                    <h5>No entry in search bar.</h5>
                </div>
            </div>
        {% endif %}
    </div>

</div>

{% endblock %}