redbrickboard/accounts/urls.py
from django.urls import path

from .views import *

app_name = "accounts"

urlpatterns = [
    path('login', login_page, name="login"),
    path('register', register, name="register"),
    path('logout', user_logout, name="logout"),
    path('auth-receiver', auth_receiver, name="auth-receiver"),
    path('profile/<int:pk>', UserProfile.as_view(), name="profile"),
    path('profile/<int:pk>/update', ProfileUpdateView.as_view(), name="profile-update")
]

# For testing:
#   path('list', UserList.as_view(), name="list"),

redbrickboard/event_management/urls.py
from django.urls import path

from .views import EventListView, EventDetailView, EventCreateView, EventUpdateView, FeaturedEventListView, delete_image, search_events, bump_event, event_rsvp, handle_attendance



urlpatterns = [
    path('', EventListView.as_view(), name='event-list'),
    path('<int:pk>/', EventDetailView.as_view(), name='event-details'),
    path('create/', EventCreateView.as_view(), name='event-create'),
    path('<int:pk>/update/', EventUpdateView.as_view(), name='event-update'),
    path('featured/', FeaturedEventListView.as_view(), name='event-featured'),
    path('int<pk>/delete-image/', delete_image, name='delete_image'),
    path('search', search_events, name='event-search'),
    path('<int:pk>/bump-event', bump_event, name="bump-event"),
    path('<int:pk>/rsvp', event_rsvp, name='event-rsvp'),
    path('<int:pk>/handle-attendance', handle_attendance, name='event-attendance'),
]

app_name = "event_management"

redbrickboard/home/urls.py
from django.urls import path

from .views import EventHomeListView

urlpatterns = [
    path('', EventHomeListView.as_view(), name='home'),
]

redbrickboard/redbrickboard/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("events/", include("event_management.urls", namespace='event_management')),
    path("", include('home.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

redbrickboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
     {% load bootstrap5 %}
     {% bootstrap_css %}
     {% bootstrap_javascript %}
     {% bootstrap_messages %}
     {% block head %}
     {% endblock %}
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta charset="utf-8">
     <link rel="stylesheet" type="text/css" href="{% static '/css/custom.css' %}">
     <link rel="icon" type="image/x-icon" href="{% static '/images/Logo.png' %}">
     {% block styles %} {% endblock %}
     <title>{% block title %}Red Brick Board{% endblock %}</title>
</head>

<body>
     <nav class="navbar navbar-expand-md sticky-top navbar-light bg-light px-md-5 px-sm-3 px-1">
          <div class="container-fluid d-flex">

               <!-- Display Logo -->
               <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static '/images/Logo with Name.png' %}" alt="Red Brick Board" class="logo me-3 me-sm-4">
               </a>

               <!-- Hamburger Icon for Navbar -->
               <button class="navbar-toggler mt-2 mb-2" type="button" data-bs-toggle="collapse" data-bs-target="#nav" aria-controls="nav" aria-expanded="false" aria-label="Toggle Navigation">
                    <span class="navbar-toggler-icon"></span>
               </button>

               <!-- Contents of Hmaburger Icon in Navbar -->
               <div class="collapse navbar-collapse justify-content-start align-items-center" id="nav">
                    <ul class="navbar-nav">
                         <li class="nav-item">
                              <a href="{% url 'event_management:event-list' %}" class="nav-link mt-1">Events</a>
                         </li>
                         <li class="nav-item">
                              <a href="{% url 'event_management:event-featured' %}" class="nav-link mt-1">Featured</a>
                         </li>
                         <li class="nav-item">
                              <a href="{% url 'event_management:event-create' %}" class="nav-link mt-1">Create</a>
                         </li>
                    </ul>
               </div>

               <!-- Next Line on Small Screen View -->
               <div class="w-100"></div>

               <!-- Display Log In/Log Out and Sign Up/My Profile -->
               <div class="container-fluid d-flex justify-content-end align-items-center pe-0">
                    {% if user.is_authenticated %}
                         <div class="col-auto">
                              <form role="Log Out" action="{% url 'accounts:logout' %}" method="post">
                                   {% csrf_token %}
                                   <button type="submit" class="btn btn-classic me-4 mt-2">Log Out</button>
                              </form>
                         </div>

                         <div class="col-auto">
                              <a href="{% url 'accounts:profile' request.user.pk %}" class="btn btn-red mt-2 px-3">My Profile</a> 
                         </div>
                    {% else %}
                         <div class="col-auto">
                              <form role="Log In" action="{% url 'accounts:login' %}" method="post">
                                   {% csrf_token %}
                                   <button type="submit" class="btn btn-classic me-4 mt-2">Log In</button>
                              </form>
                         </div>
                         
                         <div class="col-auto">
                              <a href="{% url 'accounts:register' %}" class="btn btn-red mt-2 px-4">Sign Up</a>
                         </div>
                    {% endif %}
               </div>

          </div>
     </nav>

     {% block content %}
     {% endblock %}

</body>
</html>